woodridge/core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='home'),
    path('about-us', views.about, name='about-us'),
    path('gallery', views.gallery, name='gallery'),
    path('admissions', views.admissions, name='admissions'),
    path('enquiries', views.enquiries, name='enquiries'),
    path('email-updates', views.emailupdates, name='email-updates'),

]

woodridge/woodridge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

]

woodridge/core/models.py
from django.db import models

# Create your models here.

class ParentEmails(models.Model):
    email = models.EmailField(max_length=50)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = "Parent emails"

class TourRequests(models.Model):
    full_names = models.CharField(max_length=50)
    phone_number = models.IntegerField(null=True)
    student_name = models.CharField(max_length=50)

    def __str__(self):
        return self.full_names
    
    class Meta:
        verbose_name_plural = "Tour requests"


class Applications(models.Model):
    student_first_name = models.CharField(max_length=10)
    student_second_name = models.CharField(max_length=10)
    student_class = models.CharField(max_length=5)
    kin_first_name = models.CharField(max_length=10)
    kin_surname = models.CharField(max_length=10)
    phone_number = models.IntegerField(null=True)
    any_med_condition =models.BooleanField(default=False)
    residence = models.CharField(max_length=20)

    def __str__(self):
        return f"{ self.student_first_name }  { self.student_second_name }"

    class Meta:
        verbose_name_plural = "Applications"

class Enquiries(models.Model):
    names = models.CharField(max_length=20)
    phone_number = models.IntegerField(null=True)
    query = models.CharField(max_length=50)

    def __str__(self):
        return self.names

    class Meta:
        verbose_name_plural = "Enquiries"

woodridge/core/views.py
from django.shortcuts import render, redirect
from .models import TourRequests, Enquiries, Applications, ParentEmails

# Create your views here.

def index(request):
    if request.method == "POST":
        rq = TourRequests.objects.create()
        rq.full_names = request.POST['fullname']
        rq.phone_number = request.POST['phonenumber']
        rq.student_name = request.POST['studentname']
        rq.save()
        context = {
            'messagetype' : 'success',
            'message' : 'Your request has been received. We will get in touch with you.'
        }

        return render(request, 'core/index.html', context)

    return render(request, 'core/index.html')

def emailupdates(request):
    rq = ParentEmails.objects.create()
    rq.email = request.POST['email']
    rq.save()
    context = {
        'messagetype' : 'success',
        'message' : 'Your email has been received. We will be sending emails concerning news from Woodridge.'
    }

    return render(request, 'core/index.html', context)




def about(request):
    return render(request, 'core/about-us.html')

def gallery(request):
    return render(request, 'core/gallery.html')
    
def admissions(request):
    if request.method == "POST":
        rq = Applications.objects.create()
        rq.student_first_name = request.POST['sfn']
        rq.student_second_name = request.POST['ssn']
        rq.student_class = request.POST['sclass']
        rq.kin_first_name = request.POST['kfn']
        rq.kin_surname = request.POST['kinsurname']
        rq.phone_number = request.POST['phone']
        if request.POST['condition'] == "Yes":     
            rq.any_med_condition = True
        else:
            rq.any_med_condition = False

        rq.residence = request.POST['residence']
        rq.save()
        context = {
            'messagetype' : 'success',
            'message' : 'Your application has been received. We will get in touch with you with feedback as soon as possible.'
        }

        return render(request, 'core/admissions.html', context)

    return render(request, 'core/admissions.html')

def enquiries(request):
    if request.method == "POST":
        rq = Enquiries.objects.create()
        rq.names = request.POST['names']
        rq.phone_number = request.POST['phonenumber']
        rq.query = request.POST['query']
        rq.save()
        context = {
            'messagetype' : 'success',
            'message' : 'Your query has been received. We will get in touch with you with an answer as soon as possible.'
        }

        return render(request, 'core/enquiries.html', context)

    return render(request, 'core/enquiries.html')

woodridge/core/templates/core/about-us.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}About Us | Woodridge Senior School{% endblock title %}
{% block content %}


<!-- About Start -->
<div class="container-fluid bg-secondary p-0" id="about-us">
    <div class="row g-0">
        <div class="col-lg-6 py-6 px-5">
            <h1 class="display-5 mb-4">Welcome To <span id="blue-color">Woodridge</span></h1>
            <h4 class="mb-4" id="maroon-color">We are a school that is situated along the Nyeri-Nyahururu highway.</h4>
            <p class="mb-4">Woodridge Senior School a CBC compliant and fully registered Kenyan secondary school. Our school has well-equipped science laboratories and a library. Extra-curricular activities are fully supported and we boast of a very conducive learning environment here at Woodridge.</p>
            <a href="{% url 'core:admissions' %}" class="btn py-md-3 px-md-5 rounded-pill" id="maroon-bg" style="color: white;">Apply Today</a>
        </div>
        <div class="col-lg-6">
            <div class="h-100 d-flex flex-column justify-content-center p-5" id="mainbg">
                <div class="d-flex text-white mb-5">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                        <i class="fa fa-user-tie fs-4" id="maroon-color"></i>
                    </div>
                    <div class="ps-4">
                        <h3 id="text-light">Academic Excellence</h3>
                        <p class="mb-0">Woodridge students exceed previous expectations of what they can achieve academically, whatever their starting point.</p>
                    </div>
                </div>
                <div class="d-flex text-white mb-5">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                        <i class="fa fa-chart-line fs-4" id="maroon-color"></i>
                    </div>
                    <div class="ps-4">
                        <h3 id="text-light">Skills Development</h3>
                        <p class="mb-0">Woodridge students understand, develop and model the skills and attributes required for a rewarding and satisfying career.</p>
                    </div>
                </div>
                <div class="d-flex text-white">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                        <i class="fa fa-balance-scale fs-4" id="maroon-color"></i>
                    </div>
                    <div class="ps-4">
                        <h3 id="text-light">Confidence</h3>
                        <p class="mb-0">Woodridge students are confident in their heritage, self worth, unique voice and ability to make a positive difference in the world.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <!-- About End -->

<!-- Our Offers Start -->
<div class="container-fluid pt-6 px-5">
    <div class="text-center mx-auto mb-5" style="max-width: 600px;">
        <h1 class="display-5 mb-0">What We Offer</h1>
        <hr class="w-25 mx-auto bg-primary">
    </div>
    <div class="row g-5">
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-user-tie fa-2x" id="maroon-color"></i>
                </div>
                <h3 class="mb-3">Excellent Performance</h3>
                <p class="mb-0">By our way of doing things here at Woodridge Senior School, your student is set on an upward trend on their performance.</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-chart-pie fa-2x" id="blue-color"></i>
                </div>
                <h3 class="mb-3">Extracurricular Skills</h3>
                <p class="mb-0">At Woodridge, we embrace extra-curricular activities and has lots of tools to ensure that our students can put their skills into test.</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-chart-line fa-2x" id="maroon-color"></i>
                </div>
                <h3 class="mb-3">Ready for Work</h3>
                <p class="mb-0">Woodridge students get to learn the importance of hard work and the fruits of this important key to success.</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-chart-area fa-2x" id="maroon-color"></i>
                </div>
                <h3 class="mb-3">Confidence</h3>
                <p class="mb-0">Woodridge students are taught to be confident in their own ideas and how to stand for themselves.</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-balance-scale fa-2x" id="blue-color"></i>
                </div>
                <h3 class="mb-3">Warm Relationships</h3>
                <p class="mb-0">At Woodridge, we ensure that we maintain a good and warm relationship with our students so as to ensure smoothness in the running of the school.</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-house-damage fa-2x" id="maroon-color"></i>
                </div>
                <h3 class="mb-3">Succcessful Future</h3>
                <p class="mb-0">The skills that out learners develop at Woodridge prepare them for a successful transition towards their careers.</p>
            </div>
        </div>
    </div>
  </div>
  <!-- Our Offers End -->
  
<!-- Our Promise Start -->
<div class="container-fluid py-6 px-5">
    <div class="text-center mx-auto mb-5" style="max-width: 600px;">
        <h1 class="display-5 mb-0">Our Promise</h1>
        <hr class="w-25 mx-auto bg-primary">
    </div>
    <div class="row g-5">
        <div class="col-lg-4">
            <div class="row g-5">
                <div class="col-12">
                    <div class="rounded-circle d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;" id="mainbg">
                        <i class="fa fa-cubes fs-4 text-white"></i>
                    </div>
                    <h3>Confident Individuals</h3>
                    <p class="mb-0">With our ways at Woodridge Senior School, your daughter gets to attain a level of confidence that makes her stand out.</p>
                </div>
                <div class="col-12">
                    <div class="rounded-circle d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;" id="maroon-bg">
                        <i class="fa fa-percent fs-4 text-white"></i>
                    </div>
                    <h3>Continous Improvement</h3>
                    <p class="mb-0">Every student matters, and we always believe that with continous improvement, each and every student has to excel.</p>
                </div>
                <div class="col-12">
                    <div class="rounded-circle d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;" id="mainbg">
                        <i class="fa fa-award fs-4 text-white"></i>
                    </div>
                    <h3>Responsible Citizens</h3>
                    <p class="mb-0">We always strive to produce highly responsible students here at Woodridge Senior School so they can perform future tasks with brilliance.</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="d-block h-100">
                <img src="{% static 'core/images/banner.jpg' %}" style="height: 650px;">
            </div>
        </div>
        <div class="col-lg-4">
            <div class="row g-5">
                <div class="col-12">
                    <div class="rounded-circle d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;" id="mainbg">
                        <i class="far fa-smile-beam fs-4 text-white"></i>
                    </div>
                    <h3>Maximum Potential</h3>
                    <p class="mb-0">Here at Woodridge, one of our main goals is to maximize the potential of our students.</p>
                </div>
                <div class="col-12">
                    <div class="rounded-circle d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;" id="maroon-bg">
                        <i class="fa fa-user-tie fs-4 text-white"></i>
                    </div>
                    <h3>Professional Educators</h3>
                    <p class="mb-0">With our highly professional and able staff here at Woodridge, you can be guaranteed 100% good governance for your daughter.</p>
                </div>
                <div class="col-12">
                    <div class="rounded-circle d-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;" id="mainbg">
                        <i class="fa fa-cubes fs-4 text-white"></i>
                    </div>
                    <h3>Social Responsibility</h3>
                    <p class="mb-0">We emphasize on the importance of social responsibility at Woodridge Senior School, which makes our students more responsible citizens.</p>
                </div>
            </div>
        </div>
    </div>
  </div>
  <!-- Our Promise Start -->

{% endblock content %}

woodridge/core/templates/core/admissions.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} Admissions | Woodridge Senior School {% endblock title %}
{% block content %}
<!-- Quote Start -->
<div class="container-fluid bg-secondary px-0">
    <div class="row g-0">
        {% if message %}
        <div class="text-center" id="message" style="display: block">
            <div class="alert alert-{{ messagetype }}" role="alert">
                {{ message }}
            </div>
        </div>
        {% endif %}
        <div class="col-lg-6 py-6 px-5">
            <h1 class="display-5 mb-4">Admissions</h1>
            <p class="mb-4">For admissions into Woodridge Senior School, you can visit our school in person, or you can fill in the form below and we will review your application and get to you.</p>
            <form method="POST">
                {% csrf_token %}
                <div class="row gx-3">
                    <h3 class="mb-3">Student's Information</h3>
                    <div class="col-6">
                        <div class="form-floating">
                            <input type="text" name="sfn" class="form-control" id="form-floating-1" required>
                            <label for="form-floating-1">First Name</label>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-floating mb-3">
                            <input type="text" name="ssn" class="form-control" id="form-floating-2" required>
                            <label for="form-floating-2">Second Name</label>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-floating mb-4">
                            <input type="text" name="sclass" class="form-control" id="form-floating-2" required>
                            <label for="form-floating-2">Class</label>
                        </div>
                    </div>
                    <h3 class="mb-3">Parent/Guardian's Information</h3>
                    <div class="col-6">
                        <div class="form-floating">
                            <input type="text" name="kfn" class="form-control" id="form-floating-1" required>
                            <label for="form-floating-1">First Name</label>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-floating mb-3">
                            <input type="text" name="kinsurname" class="form-control" id="form-floating-2" required>
                            <label for="form-floating-2">Surname</label>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-floating mb-4">
                            <input type="number" name="phone" class="form-control" id="form-floating-2" required>
                            <label for="form-floating-2">Phone Number</label>
                        </div>
                    </div>
                    <h3 class="mb-3">Other Information</h3>
                    <div class="col-12">
                        <div class="form-floating mb-4">
                            <select class="form-control" name="condition" id="exampleFormControlSelect1">
                                <option>No</option>
                                <option>Yes</option>
                              </select>
                            <label for="form-floating-2">Does your daughter suffer from any condition?</label>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-floating mb-4">
                            <input type="text" name="residence" class="form-control" id="form-floating-2" required>
                            <label for="form-floating-2">Where do you reside?</label>
                        </div>
                    </div>
                    <div class="col-12 mt-3">
                        <button class="btn btn-primary w-100" style="height: 70px" type="submit">Submit Admission</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-6 d-none d-md-block" style="height: 1325px;">
            <div class="position-relative h-100">
                <img class="position-absolute w-100 h-100" src="{% static 'core/images/banner2.jpg' %}" style="object-fit: cover;">
            </div>
        </div>
    </div>
  </div>
  <!-- Quote End -->
{% endblock content %}

woodridge/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Favicon -->
    <link href="{% static 'core/images/logo.jpg' %}" rel="icon">

    <meta name=description content="Woodridge Senior School, in Pursuit Of Excellence">
    <meta name=keywords content="Woodridge, Senior, School, Secondary, High, Kenya">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'core/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet">
</head>

<div>
    <!-- Topbar Start -->
    <div class="container-fluid bg-secondary ps-5 pe-0 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-md-4 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    <a class="text-body py-2 pe-3 border-end"><small>FAQs</small></a>
                    <a class="text-body py-2 px-3 border-end"><small>Support</small></a>
                    <a class="text-body py-2 px-3 border-end"><small>Suggestions</small></a>
                    <a class="text-body py-2 px-3"><small>Rules & Regulations</small></a>
                </div>
            </div>
            <div class="col-md-8 text-center text-lg-end">
                <div class="position-relative d-inline-flex align-items-center text-white top-shape px-5" id="mainbg">
                    <div class="me-3 pe-3 py-2">
                        <p class="m-0"><i class="fa fa-envelope-open me-2"></i>woodridgesenior@gmail.com</p>
                    </div>
                    <div class="py-2  me-3 pe-3">
                        <a href="https://www.facebook.com/InPursuitofDistinction" target="_blank"><p class="m-0" style="color: white;"><i class="fab fa-facebook-f me-2"></i>Woodridge Senior School</p></a>
                    </div>
                    <div class="py-2 me-3 pe-3">
                        <p class="m-0"><i class="fa fa-phone-alt me-2"></i>+254 722610911</p>
                    </div>
                    <div class="py-2">
                        <p class="m-0"><i class="fa fa-phone-alt me-2"></i>+254 722438406</p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm px-5 py-3 py-lg-0">
        <a href="{% url 'core:home' %}" class="navbar-brand p-0">
            <img src="{% static 'core/images/logo.jpg' %}" id="logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 me-n3">
                <a href="{% url 'core:home' %}" class="nav-item nav-link" id="maroon-color">Home</a>
                <a href="{% url 'core:about-us' %}" class="nav-item nav-link" id="maroon-color">About Us</a>
                <a href="{% url 'core:gallery' %}" class="nav-item nav-link" id="maroon-color">Gallery</a>
                <a href="#contact-us" class="nav-item nav-link" id="maroon-color">Contact Us</a>
                <a href="{% url 'core:admissions' %}" class="nav-item nav-link" id="maroon-color">Admissions</a>
                <a href="{% url 'core:enquiries' %}" class="nav-item nav-link" id="maroon-color">Enquiries</a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->
    {% block content %}{% endblock content %}
    <!-- Footer Start -->
    <section id="contact-us">
    <div class="container-fluid text-secondary p-5" id="mainbg">
        <div class="row g-5">
            <div class="col-12 text-center">
                <h1 class="mb-4 text-sm" id="text-light">To stay updated on all the latest news, please enter your email below.</h1>
                <form method="POST" action="email-updates" class="mx-auto" style="max-width: 600px;">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="email" name="email" class="form-control border-white p-3" placeholder="Your Email">
                        &nbsp; &nbsp;
                        <button class="btn px-4" name="submit" id="background-light">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-secondary p-5">
        <div class="row g-5">
            <div class="col-lg-4 col-md-6">
                <h3 class="text-white mb-4">Quick Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-secondary mb-2" href="{% url 'core:home' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-secondary mb-2" href="{% url 'core:about-us' %}"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-secondary mb-2" href="{% url 'core:gallery' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Gallery</a>
                    <a class="text-secondary mb-2" href="{% url 'core:admissions' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Admissions</a>
                    <a class="text-secondary mb-2" href="{% url 'core:enquiries' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Enquiries</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>P.O Box 1805 - 10100 Nyeri</p>
                <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>woodridgesenior@gmail.com</p>
                <p class="mb-2"><i class="bi bi-telephone text-primary me-2"></i>+254722438406</p>
                <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>+254722610911</p>
            </div>
            <div class="col-lg-4 col-md-6">
                <h3 class="text-white mb-4">Follow Us</h3>
                <div class="d-flex">
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2"><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="https://www.facebook.com/InPursuitofDistinction" target="_blank"><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2"><i class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle"><i class="fab fa-instagram fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-secondary text-center border-top py-4 px-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <p class="m-0">&copy; <a class="text-secondary border-bottom">Woodridge Senior School</a>. All Rights Reserved. Designed by <a class="text-secondary border-bottom">Realm Tech</a></p>
    </div>
</section>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'core/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'core/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'core/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'core/js/main.js' %}"></script>
    <script>

        setTimeout(() => {

        const message = document.getElementById("message");

        message.style.display = 'none';


        }, 5000);
    </script>
</body>

</html>